trigger:
  branches:
    include:
    - main

schedules:
- cron: "0 2 * * *"  # 2 AM daily
  displayName: Nightly runner image build
  branches:
    include:
    - main
  always: true

variables:
  resourceGroup: 'rg-agents'
  location: 'norwayeast'
  imageGalleryName: 'agentImageGallery'
  imageDefinitionName: 'Ubuntu2204'
  vmssName: 'vmss-kai-agents'
  agentPool: 'KaisPool'
  runnerImagesRepo: 'https://github.com/actions/runner-images.git'
  runnerImagesRef: 'main'  # or specific release tag
  Agent.WorkFolder: /home/kaithors/agent/_work
  Agent.HomeDirectory: /home/kaithors/agent

stages:
- stage: BuildRunnerImage
  displayName: 'Build Microsoft-Compatible Runner Image'
  jobs:
  - job: BuildImage
    displayName: 'Build Ubuntu 22.04 Runner Image'
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 180  # These builds can take a while
    steps:
    - task: AzureCLI@2
      displayName: 'Setup Azure Resources'
      inputs:
        azureSubscription: 'your-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create resource group if not exists
          az group create -n $(resourceGroup) -l $(location) || true
          
          # Create shared image gallery if not exists
          az sig create \
            --resource-group $(resourceGroup) \
            --gallery-name $(imageGalleryName) || true
          
          # Create image definition if not exists
          az sig image-definition create \
            --resource-group $(resourceGroup) \
            --gallery-name $(imageGalleryName) \
            --gallery-image-definition $(imageDefinitionName) \
            --publisher Microsoft \
            --offer UbuntuServer \
            --sku 22.04-LTS \
            --os-type Linux \
            --os-state Generalized || true

    - script: |
        # Clone runner-images repository
        git clone $(runnerImagesRepo) runner-images
        cd runner-images
        git checkout $(runnerImagesRef)
        
        # Copy our custom configuration
        cp $(System.DefaultWorkingDirectory)/packer/azure-devops-config.json images/ubuntu/templates/
      displayName: 'Clone Runner Images Repository'

    - task: PackerBuild@1
      displayName: 'Build Runner Image with Packer'
      inputs:
        templateType: 'custom'
        customTemplateLocation: 'runner-images/images/ubuntu/ubuntu-22.04.pkr.hcl'
        customTemplateParameters: |
          {
            "client_id": "$(ARM_CLIENT_ID)",
            "client_secret": "$(ARM_CLIENT_SECRET)",
            "tenant_id": "$(ARM_TENANT_ID)",
            "subscription_id": "$(ARM_SUBSCRIPTION_ID)",
            "managed_image_resource_group_name": "$(resourceGroup)",
            "gallery_name": "$(imageGalleryName)",
            "gallery_image_definition": "$(imageDefinitionName)",
            "location": "$(location)",
            "vm_size": "Standard_D4s_v4"
          }
        packerVersion: '1.9.4'

    - script: |
        # The runner-images build process creates detailed software reports
        echo "## Installed Software Report" > $(Build.ArtifactStagingDirectory)/software-report.md
        cat runner-images/images/ubuntu/software-report.md >> $(Build.ArtifactStagingDirectory)/software-report.md
      displayName: 'Generate Software Report'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'SoftwareReport'